import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const BarlowCondensed = localFont({
  src: "./fonts/BarlowCondensed-Black.ttf",
  variable: "--font-barlow-condensed",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Meaty® - The Burger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${BarlowCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
